GET http://localhost:3000/events

###
GET http://localhost:3000/events/5f0079278d3e4fbac2a81f61

###
GET http://localhost:3000/user

###
GET http://localhost:3000/login

###
GET http://localhost:3000/register/organizer

###
GET http://localhost:3000/register/dancer

###
GET http://localhost:3000/users

###
GET http://localhost:3000/users/5f0078518d3e4fbac2a81f5d