###
DELETE http://localhost:3000/events/5efc30b33499c85e90e4f859
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjVlZmMxZjA1NWI3ZWQzNTllM2MwMzBiYSIsImVtYWlsIjoidGVzdEB0ZXN0LmRlIn0sImlhdCI6MTU5MzU4MzI1MH0.tck2Tw_TvEe6QTd97iPWXMvIcq6ZO4ajz9PKCYQPOPk