GET http://localhost:3000/events

###
GET http://localhost:3000/events/1

###
GET http://localhost:3000/user

###
GET http://localhost:3000/login

###
GET http://localhost:3000/register/organizer

###
GET http://localhost:3000/register/dancer

###
GET http://localhost:3000/users

###
GET http://localhost:3000/users/5efb9c0fd1b9713f9c7c32cc