###
POST http://localhost:3000/register/organizer HTTP/1.1
content-type: application/json

{
    "email": "test@test.de",
    "password": "1234",
    "name": "test organizer",
    "city": "Munich",
    "street": "Kaufinger Straße",
    "description": "great organizer",
    "publicEmail": "publictest@test.de",
    "phone": "7654387"
}

###
POST http://localhost:3000/register/dancer HTTP/1.1
content-type: application/json

{
    "email": "testdancer@test.de",
    "password": "1234",
    "name": "test dancer",
    "city": "Munich",
    "interestedInEvents": "5efc30b13499c85e90e4f858",
    "gender": "male",
    "height": 182,
    "yearOfBirth": 1996,
    "listOfDanceStyles": ["hustle", "mambo"],
    "proficiencyLevel": "beginner",
    "description": "great dancer",
    "prefAgeMin": 20,
    "prefAgeMax": 30,
    "prefGender": "female"
}

###
POST http://localhost:3000/login HTTP/1.1
content-type: application/json

{
    "email": "test@test.de",
    "password": "1234"
}

###
POST http://localhost:3000/events HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjVmMDA3ODUxOGQzZTRmYmFjMmE4MWY1ZCIsImVtYWlsIjoidGVzdEB0ZXN0LmRlIn0sImlhdCI6MTU5NDg1MzI4OH0.AtF0ZcH4ayLDcKpzhHfJwjdlOKhHbxhu6iJAdq7MpuI

{
    "title": "Dance Party Neubeck",
    "type": "party",
    "organizer": "5efc1f055b7ed359e3c030ba",
    "description": "Come to our great party!",
    "startDate": "2020-06-12T19:00:00",
    "endDate": "2020-06-13T02:00:00",
    "city": "Munich",
    "location": "some location",
    "listOfDanceStyles": ["mambo", "jive"],
    "listOfProficiencyLevels": ["beginner"],
    "price": "7",
    "promoCode": "NEUBECK05"
}

###
POST http://localhost:3000/events HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjVmMDA3ODUxOGQzZTRmYmFjMmE4MWY1ZCIsImVtYWlsIjoidGVzdEB0ZXN0LmRlIn0sImlhdCI6MTU5NDg1MzI4OH0.AtF0ZcH4ayLDcKpzhHfJwjdlOKhHbxhu6iJAdq7MpuI

{
    "title": "ein fancy tanzball",
    "type": "ball",
    "organizer": "5f0078518d3e4fbac2a81f5d",
    "description": "Es gibt was zu feiern!",
    "startDate": "2020-07-08T19:00:00",
    "endDate": "2020-07-09T00:00:00",
    "city": "Munich",
    "location": "some location",
    "listOfDanceStyles": ["mambo", "jive"],
    "listOfProficiencyLevels": ["beginner"],
    "price": "7",
    "promoCode": "NEUBECK05"
}

###
POST http://localhost:3000/events HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjVmMDA3ODUxOGQzZTRmYmFjMmE4MWY1ZCIsImVtYWlsIjoidGVzdEB0ZXN0LmRlIn0sImlhdCI6MTU5NDg1MzI4OH0.AtF0ZcH4ayLDcKpzhHfJwjdlOKhHbxhu6iJAdq7MpuI

{
    "title": "noch ein event",
    "type": "ball",
    "organizer": "5f0078518d3e4fbac2a81f5d",
    "description": "Es gibt was zu feiern!",
    "startDate": "2020-07-09T19:00:00",
    "endDate": "2020-07-09T23:00:00",
    "city": "Munich",
    "location": "some location",
    "listOfDanceStyles": ["mambo", "jive"],
    "listOfProficiencyLevels": ["beginner"],
    "price": "7",
    "promoCode": "NEUBECK05"
}

###
POST http://localhost:3000/events HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjVmMDA3ODUxOGQzZTRmYmFjMmE4MWY1ZCIsImVtYWlsIjoidGVzdEB0ZXN0LmRlIn0sImlhdCI6MTU5NDg1MzI4OH0.AtF0ZcH4ayLDcKpzhHfJwjdlOKhHbxhu6iJAdq7MpuI

{
    "title": "und noch eins",
    "type": "party",
    "organizer": "5f0078518d3e4fbac2a81f5d",
    "description": "Es gibt was zu feiern!",
    "startDate": "2020-07-08T03:00:00",
    "endDate": "2020-07-08T05:00:00",
    "city": "Munich",
    "location": "some location",
    "listOfDanceStyles": ["mambo", "jive"],
    "listOfProficiencyLevels": ["beginner"],
    "price": "7",
    "promoCode": "NEUBECK05"
}

###
POST http://localhost:3000/events HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjVmMDA3ODUxOGQzZTRmYmFjMmE4MWY1ZCIsImVtYWlsIjoidGVzdEB0ZXN0LmRlIn0sImlhdCI6MTU5NDg1MzI4OH0.AtF0ZcH4ayLDcKpzhHfJwjdlOKhHbxhu6iJAdq7MpuI

{
    "title": "1 nica dance course",
    "type": "course",
    "organizer": "5efc1f055b7ed359e3c030ba",
    "description": "hier wird gedancet",
    "startDate": "2020-07-20T18:00:00",
    "endDate": "2020-07-23T23:00:00",
    "city": "Valencia",
    "location": "Akuarela Playa",
    "listOfDanceStyles": ["hustle", "various"],
    "listOfProficiencyLevels": ["beginner", "intermediate"],
    "price": "9999",
    "promoCode": "TECHNO",
    "interval": "daily"
}

### Fetch the profile using a POST request
POST http://localhost:3000/profile HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjVmMDA3ODUxOGQzZTRmYmFjMmE4MWY1ZCIsImVtYWlsIjoidGVzdEB0ZXN0LmRlIn0sImlhdCI6MTU5Mzk1ODczN30.BolEpAMAp6g4ZBppvTIHsAnAwGfqwMk3pQ4N0MAqAcg